name: agora_rtm
description: Flutter wrapper around the Agora Real Time Message SDKs for Android and iOS.
version: 2.2.2
homepage: https://www.agora.io
repository: https://github.com/AgoraIO-Extensions/Agora-Flutter-RTM-SDK.git
environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.10.0
  ffi: '>=2.1.5'
  async: '>=2.13.0'
  meta: '>=1.18.1'
  iris_method_channel: '>=2.2.4'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=6.0.0'
  build_runner: ^2.10.5
  json_serializable: ^6.12.0
  ffigen: ^20.1.1
flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agorartm.agora_rtm
        pluginClass: AgoraRtmPlugin
      ios:
        pluginClass: AgoraRtmPlugin
